### ISSUE TITLE
already annotated documents presented during annotation session

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/image-tagger-api#7]
During annotation sessions, the user is occasionally (i.e., rarely, but with multiple recurrences observed) presented with an already annotated document, with annotations visualized in the interface.  These are skipped over easily by selecting "next image" but should check on this. Will try to post doc ids when next occurrence happens.

**Comment by cambro** [comment]
example: doc id that returned already annotated document during annotation session:
4501612e-a922-4d83-a819-30952c396d03

**Comment by cambro** [comment]
@iross @jczaplew any obvious reasons for the above doc_ids entering into annotation interface after being annotated?

**Comment by jczaplew** [comment]
Let's see if f75636dc88f20b9caa3a8eef6dafe6a924258adf fixes it
